name: Daily XML Processing

on:
  schedule:
    - cron: '0 6 * * *'  # Executa às 6:00 UTC diariamente
  workflow_dispatch:
    inputs:
      channel:
        description: 'Canal específico para processar'
        required: false
        type: string
      offset:
        description: 'Offset específico em segundos'
        required: false
        type: string
      force_download:
        description: 'Forçar download'
        required: false
        type: boolean
        default: false

jobs:
  process-xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p data/raw data/processed data/reports logs
        
    - name: Process XML with channel-specific settings
      run: |
        if [ "${{ github.event.inputs.channel }}" != "" ] && [ "${{ github.event.inputs.offset }}" != "" ]; then
          echo "Processando canal específico: ${{ github.event.inputs.channel }} com offset ${{ github.event.inputs.offset }}"
          python run.py --channel "${{ github.event.inputs.channel }}" --channel-offset "${{ github.event.inputs.offset }}" --save-config
        else
          echo "Processando todos os canais"
          python run.py
        fi
        
    - name: Upload processed files
      uses: actions/upload-artifact@v3
      with:
        name: processed-epg
        path: data/processed/
        
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: processing-reports
        path: data/reports/
        
    - name: Commit updated configuration
      if: github.event.inputs.channel != '' && github.event.inputs.offset != ''
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add config/channel-offsets.json
        git diff --staged --quiet || git commit -m "Ajuste automático: canal ${{ github.event.inputs.channel }} -> ${{ github.event.inputs.offset }}s"
        git push
